# Generated by Django 5.2.1 on 2025-05-22 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha_Dom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_fecha', models.DateField(blank=True, null=True)),
                ('total_personas', models.IntegerField()),
                ('encuestador', models.CharField(default='', max_length=50)),
                ('ficha_numero', models.CharField(default='', max_length=50)),
                ('provincia', models.BooleanField()),
                ('partido', models.BooleanField()),
                ('municipio', models.BooleanField()),
                ('localidad', models.BooleanField()),
                ('barrio', models.BooleanField()),
                ('fraccion', models.BooleanField()),
                ('radio', models.BooleanField()),
                ('area', models.BooleanField()),
                ('paraje', models.BooleanField()),
                ('comunidad', models.BooleanField()),
                ('calle_tipo', models.BooleanField()),
                ('calle', models.BooleanField()),
                ('altura', models.BooleanField()),
                ('piso', models.BooleanField()),
                ('departamento', models.BooleanField()),
                ('torre_pasillo_escalera', models.BooleanField()),
                ('entre_calle', models.BooleanField()),
                ('y_calle', models.BooleanField()),
                ('cp', models.BooleanField()),
                ('manzana', models.BooleanField()),
                ('telefono', models.BooleanField()),
                ('vivienda_ubicada', models.BooleanField()),
                ('vivienda_tipo', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha_Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_persona', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=50)),
                ('fecha_nacimiento', models.BooleanField()),
                ('años', models.BooleanField()),
                ('meses', models.BooleanField()),
                ('sexo', models.BooleanField()),
                ('genero', models.BooleanField()),
                ('apellido', models.BooleanField()),
                ('parentesco_jefe', models.BooleanField()),
                ('situacion_conyugal', models.BooleanField()),
                ('pareja_de', models.BooleanField()),
                ('madre_padre1', models.BooleanField()),
                ('madre_padre2', models.BooleanField()),
                ('documento_tipo', models.BooleanField()),
                ('documento', models.BooleanField()),
                ('pais', models.BooleanField()),
                ('indigena', models.BooleanField()),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.ficha_dom')),
            ],
        ),
    ]
