# Generated by Django 5.2.1 on 2025-05-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_ficha_dom_agua_proviene_ficha_dom_asistio1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha_dom',
            name='cronica1',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha_dom',
            name='cronica2',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
