# Generated by Django 5.2.1 on 2025-06-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_product_agua_proviene_product_altura_product_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='apellido',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='años',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='documento',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='documento_tipo',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='fecha_nacimiento',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='genero',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='indigena',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='madre_padre1',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='madre_padre2',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='meses',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='variant',
            name='nro_persona',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variant',
            name='pais',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='pareja_de',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='parentesco_jefe',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='sexo',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='situacion_conyugal',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
