# Generated by Django 5.2.1 on 2025-06-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_remove_product_short_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha_personas',
            name='ficha',
        ),
        migrations.DeleteModel(
            name='Ficha_Dom',
        ),
        migrations.DeleteModel(
            name='Ficha_Personas',
        ),
    ]
