# Generated by Django 5.2.1 on 2025-06-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_remove_ficha_personas_ficha_delete_ficha_dom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
