# Generated by Django 5.2.1 on 2025-06-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_variant_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='contadas2',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='fecha',
        ),
    ]
