# Generated by Django 5.2.1 on 2025-06-23 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_remove_variant_contadas2_remove_variant_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relevamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('año', models.IntegerField(default=0)),
                ('sup_fecha', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='relevamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.relevamiento'),
        ),
        migrations.DeleteModel(
            name='Calificacion',
        ),
    ]
