# Generated by Django 5.2.1 on 2025-06-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_relevamiento_product_relevamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='obs',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='omision_miembros',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
