# Generated by Django 5.2.1 on 2025-07-03 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_product_obs_product_omision_miembros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='obs',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='relevamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='todo.relevamiento'),
        ),
    ]
