# Generated by Django 5.2.1 on 2025-07-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_alter_product_obs_alter_product_relevamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inclusion_miembros',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='respondente_valido',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
